esphome:
  name: nodemcu1
  friendly_name: NodeMCU#1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fCnLI/x64L5jKDPSuaVgLZ4lBrGasmWK1HEIylxMmf4="

ota:
  password: "8cb8b208ed9b7c8a6cf00f81bba4b84b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu1 Fallback Hotspot"
    password: "QvwF9PIwxKtO"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
    name: "Motion Detector"
    device_class: motion
    filters:
      - delayed_off: 10ms

output:
  - platform: gpio
    pin: GPIO14
    id: gpio_d5_led

light:
  - platform: binary
    output: gpio_d5_led
    name: "ESP8266_D5_LED"
    id: my_blinking_light
    internal: true    # This hides the 'light' platform from Home Assistant 

globals:
  - id: should_blink
    type: bool
    restore_value: no
    initial_value: 'true'

switch:
  - platform: template
    name: "Toggle Flashing"
    id: toggle_flashing
    lambda: |- 
      return id(should_blink);
    turn_on_action:
      - globals.set:
          id: should_blink
          value: 'true'
    turn_off_action:
      - globals.set:
          id: should_blink
          value: 'false'
      - light.turn_off: my_blinking_light

interval:
  - interval: 1s
    then:
      - if:
          condition:
            lambda: 'return id(should_blink);'
          then:
            - light.toggle: my_blinking_light
